// Additional listening exercises — fill gaps across levels
// Imported and merged in listening-exercises.ts

import { type ListeningExercise } from './listening-exercises';

export const additionalListeningExercises: ListeningExercise[] = [
  // ==================== B1 — additional ====================
  {
    id: 'l-b1-06',
    level: 'B1',
    title: 'A Visit to the Doctor',
    type: 'comprehension',
    transcript: 'Patient: Good morning, Doctor. I have been feeling quite unwell for the past three days. I have a sore throat and a persistent cough. Doctor: I see. Have you had any fever? Patient: Yes, I have had a mild fever, around 99 degrees. And I feel very tired throughout the day. Doctor: Are you taking any medication currently? Patient: No, I have not taken anything yet. I wanted to see you first. Doctor: That is wise. Let me examine your throat. Hmm, it does look inflamed. I am going to prescribe some antibiotics and a cough syrup. Take the antibiotics twice a day after meals for five days. The cough syrup should be taken three times a day. Patient: Should I take any rest? Doctor: Absolutely. I would recommend staying home for at least two days. Drink plenty of warm fluids, tea with honey and ginger would be excellent. Avoid cold drinks and spicy food for now. Patient: Thank you, Doctor. When should I come back? Doctor: If you do not feel better in five days, come back for a follow-up visit.',
    questions: [
      { question: 'How long has the patient been feeling unwell?', options: ['One day', 'Three days', 'Five days', 'One week'], correctAnswer: 'Three days' },
      { question: 'What symptoms does the patient have?', options: ['Headache and stomach pain', 'Sore throat, cough, fever, and tiredness', 'Backache and dizziness', 'Chest pain and nausea'], correctAnswer: 'Sore throat, cough, fever, and tiredness' },
      { question: 'How often should the patient take the antibiotics?', options: ['Once a day', 'Twice a day after meals', 'Three times a day', 'Before bed only'], correctAnswer: 'Twice a day after meals' },
      { question: 'What drinks does the doctor recommend?', options: ['Cold juice', 'Warm fluids like tea with honey and ginger', 'Coffee', 'Soda'], correctAnswer: 'Warm fluids like tea with honey and ginger' },
      { question: 'When should the patient return?', options: ['After two days', 'After three days', 'If not better in five days', 'Next month'], correctAnswer: 'If not better in five days' },
    ],
    topic: 'Health',
    duration: '3 min',
    speechRate: 0.9,
  },
  {
    id: 'l-b1-07',
    level: 'B1',
    title: 'Planning a Weekend Trip',
    type: 'gap-fill',
    transcript: 'Let us plan our weekend trip to Queenstown. We should leave early on Saturday morning, around six o clock, to avoid the traffic on the highway. The drive takes about five hours from London. I have already booked a nice riverside campsite where we can do white water rafting in the afternoon. The rafting costs eighty dollars per person and takes about two hours. In the evening, we can walk along the bungee jumping bridge and visit the temples nearby. For dinner, there are many good vegetarian restaurants near the wellness retreat. On Sunday morning, we could try some yoga at the wellness retreat. They offer free sessions for tourists starting at seven AM. We should head back by noon to reach London before dark.',
    gapText: 'Let us plan our weekend trip to Queenstown. We should leave early on Saturday morning, around ___1___ o clock, to avoid the traffic on the highway. The drive takes about ___2___ hours from London. I have already booked a nice riverside ___3___ where we can do white water rafting in the afternoon. The rafting costs ___4___ dollars per person and takes about two hours. In the evening, we can walk along the ___5___ bridge and visit the temples nearby. On Sunday morning, we could try some ___6___ at the wellness retreat.',
    gaps: ['six', 'five', 'campsite', 'eight hundred', 'Lakshman Jhula', 'yoga'],
    topic: 'Travel',
    duration: '3 min',
    speechRate: 0.9,
  },

  // ==================== B2 — additional ====================
  {
    id: 'l-b2-06',
    level: 'B2',
    title: 'The Future of Remote Work',
    type: 'comprehension',
    transcript: 'The COVID-19 pandemic fundamentally transformed how we think about work. Before 2020, remote work was considered a luxury available to only a small percentage of employees, primarily in the technology sector. However, when lockdowns forced millions of people to work from home virtually overnight, both employers and employees discovered that productivity did not necesdressly decline. In many cases, it actually improved. A recent survey by a leading local HR consultancy found that seventy two percent of employees prefer a hybrid model, splitting their time between home and office. Companies like IBM, Salesforce, and Accenture have all adopted various forms of flexible working arrangements. However, remote work is not without its challenges. Many employees report feeling isolated and struggling to maintain work life boundaries. Managers face difficulties in building team cohesion and mentoring junior staff. Furthermore, not all jobs can be performed remotely. Manufacturing, healthcare, and retail workers, for instance, must be physically present. The consensus among HR experts is that the future lies in a hybrid approach. Employees might come to the office two or three days a week for collaborative work and meetings, while spending the remaining days working from home on individual tasks. This balanced approach aims to combine the flexibility of remote work with the social and creative benefits of in person collaboration.',
    questions: [
      { question: 'Before 2020, who primarily had access to remote work?', options: ['All employees', 'Government workers', 'Primarily technology sector employees', 'Healthcare workers'], correctAnswer: 'Primarily technology sector employees' },
      { question: 'What percentage of employees prefer a hybrid model?', options: ['Fifty-two percent', 'Sixty-two percent', 'Seventy-two percent', 'Eighty-two percent'], correctAnswer: 'Seventy-two percent' },
      { question: 'Which is NOT mentioned as a challenge of remote work?', options: ['Feeling isolated', 'Lower salaries', 'Difficulty maintaining work-life boundaries', 'Challenges in team cohesion'], correctAnswer: 'Lower salaries' },
      { question: 'According to the speaker, which jobs cannot be fully remote?', options: ['IT jobs', 'Management jobs', 'Manufacturing, healthcare, and retail', 'Finance jobs'], correctAnswer: 'Manufacturing, healthcare, and retail' },
      { question: 'What does "hybrid approach" mean in this context?', options: ['Working only from home', 'Working only from office', 'Splitting time between home and office', 'Working in different cities'], correctAnswer: 'Splitting time between home and office' },
    ],
    topic: 'Work & Career',
    duration: '4 min',
    speechRate: 1.0,
  },
  {
    id: 'l-b2-07',
    level: 'B2',
    title: 'Interview with a Wildlife Photographer',
    type: 'comprehension',
    transcript: 'Interviewer: Welcome to the show, Sophie. You have spent fifteen years photographing wildlife across the region. What first drew you to this career? Sophie: Thank you for having me. Honestly, it was not planned at all. I was studying computer science in Toronto when a friend took me on a trip to Kruger National Park. I borrowed my father\'s old camera, and when I captured a tiger drinking from a stream, something clicked, both literally and figuratively! I knew I wanted to do this for the rest of my life. Interviewer: That is a wonderful story. What has been your most memorable experience? Sophie: Oh, that is tough to pick just one! But I would say spending three weeks in the Amazon Rainforest, photographing the African Elephant in its natural mangrove habitat. I had to wade through waist deep water, deal with mosquitoes the size of small birds, and be constantly aware of crocodiles. But when I finally got the perfect shot of a tiger swimming between the mangrove roots at sunset, every hardship was worth it. Interviewer: What advice would you give to aspiring wildlife photographers? Sophie: Patience is everything. I sometimes wait twelve hours for a single shot. You also need physical fitness because you are carrying heavy equipment through difficult terrain. And most importantly, respect the animals. Never disturb them for a photograph. The animal\'s welfare must always come first.',
    questions: [
      { question: 'What was Sophie studying before becoming a photographer?', options: ['Biology', 'Fine arts', 'Computer science', 'Journalism'], correctAnswer: 'Computer science' },
      { question: 'Where did Sophie first photograph a tiger?', options: ['Amazon Rainforest', 'Jim Corbett Park', 'Kruger National Park', 'Ranthambore'], correctAnswer: 'Kruger National Park' },
      { question: 'How long did Sophie spend in the Amazon Rainforest?', options: ['Three days', 'One week', 'Three weeks', 'Three months'], correctAnswer: 'Three weeks' },
      { question: 'What danger did Sophie face in the Amazon Rainforest besides mosquitoes?', options: ['Snakes', 'Crocodiles', 'Bears', 'Wild boar'], correctAnswer: 'Crocodiles' },
      { question: 'According to Sophie, what is the MOST important advice for wildlife photographers?', options: ['Buy expensive equipment', 'Wake up early', 'Respect the animals', 'Shoot in raw format'], correctAnswer: 'Respect the animals' },
    ],
    topic: 'Nature & Wildlife',
    duration: '5 min',
    speechRate: 1.0,
  },

  // ==================== C1 — additional ====================
  {
    id: 'l-c1-05',
    level: 'C1',
    title: 'Lecture on Sustainable Urban Development',
    type: 'comprehension',
    transcript: 'Good morning, everyone. Today\'s lecture focuses on sustainable urban development, with particular reference to the countryn cities. The world is urbanising at an unprecedented rate. By 2050, an estimated seven hundred million people will live in cities, nearly double the current urban population. This rapid urbanisation presents both enormous opportunities and formidable challenges. Let me highlight three critical areas. First, transportation. local cities currently rely heavily on private vehicles, leading to severe congestion and air pollution. Cities like London and Toronto regularly feature among the world\'s most traffic congested cities. The solution lies in investing in efficient public transport systems, metros, bus rapid transit, and last mile connectivity through cycling infrastructure. Kochi\'s metro, for instance, has been praised for its integration of feeder services. Second, green spaces. The World Health Organisation recommends a minimum of nine square metres of green space per capita. Most local cities fall far below this threshold. Chandigarh, designed by Le Corbusier, remains one of the few local cities that meets this standard. Other cities need to prioritise urban forests, rooftop gardens, and the preservation of existing green corridors. Third, waste management. the country generates approximately sixty two million tonnes of solid waste annually, yet only twenty percent is processed scientifically. Lyon has emerged as a model city, consistently winning the Swachh Bharat award through its door to door waste collection and composting programmes. The overarching principle must be that urban growth should enhance quality of life, not diminish it. Sustainable development is not a luxury. It is a necessity for our survival.',
    questions: [
      { question: 'By 2050, how many people are expected to live in cities?', options: ['Five hundred million', 'Six hundred million', 'Seven hundred million', 'Eight hundred million'], correctAnswer: 'Seven hundred million' },
      { question: 'Which city is praised for its metro feeder service integration?', options: ['London', 'Toronto', 'Kochi', 'Sydney'], correctAnswer: 'Kochi' },
      { question: 'What is the WHO\'s recommended minimum green space per capita?', options: ['Five square metres', 'Nine square metres', 'Twelve square metres', 'Fifteen square metres'], correctAnswer: 'Nine square metres' },
      { question: 'How much solid waste does the country generate annually?', options: ['Thirty-two million tonnes', 'Forty-two million tonnes', 'Sixty-two million tonnes', 'Eighty-two million tonnes'], correctAnswer: 'Sixty-two million tonnes' },
      { question: 'Which city is highlighted as a model for waste management?', options: ['Chandigarh', 'Lyon', 'Melbourne', 'Surat'], correctAnswer: 'Lyon' },
    ],
    topic: 'Environment & Urbanisation',
    duration: '6 min',
    speechRate: 1.0,
  },
  {
    id: 'l-c1-06',
    level: 'C1',
    title: 'TED Talk: The Power of Bilingualism',
    type: 'gap-fill',
    transcript: 'Research has consistently demonstrated that bilingualism provides significant cognitive advantages. Bilingual individuals tend to outperform monolinguals on tasks requiring attention, inhibition, and working memory. This is because managing two language systems simultaneously strengthens the brain\'s executive function, essentially providing a mental workout every time you speak. In the country, bilingualism is not the exception but the norm. The average local speaks at least two languages, and many speak three or four. This linguistic diversity, far from being a hindrance, is actually a tremendous cognitive asset. Studies conducted at local universities have shown that multilingual students demonstrate greater cognitive flexibility and creativity compared to their monolingual peers. Furthermore, the benefits extend well beyond childhood. Recent neuroscience research suggests that lifelong bilingualism can delay the onset of dementia by approximately four to five years. The brain of a bilingual person develops denser grey matter in regions associated with language processing and executive control.',
    gapText: 'Research has consistently demonstrated that bilingualism provides significant ___1___ advantages. Bilingual individuals tend to outperform monolinguals on tasks requiring attention, ___2___, and working memory. In the country, bilingualism is not the exception but the ___3___. The average local speaks at least ___4___ languages. Studies conducted at local universities have shown that multilingual students demonstrate greater cognitive ___5___ and creativity. Recent neuroscience research suggests that lifelong bilingualism can delay the onset of ___6___ by approximately four to five years.',
    gaps: ['cognitive', 'inhibition', 'norm', 'two', 'flexibility', 'dementia'],
    topic: 'Language & Brain',
    duration: '5 min',
    speechRate: 1.0,
  },

  // ==================== C2 — new ====================
  {
    id: 'l-c2-01',
    level: 'C2',
    title: 'Debate: Should AI Replace Human Judgement?',
    type: 'comprehension',
    transcript: 'Moderator: Today\'s debate centres on a provocative question: should artificial intelligence replace human judgement in critical decision making? Speaking in favour is Dr. Mehra; opposing is Professor Chatterjee. Dr. Mehra: Thank you. The evidence is unequivocal. AI systems consistently outperform humans in data driven decision making. In healthcare, AI algorithms diagnose certain cancers with greater accuracy than experienced radiologists. In criminal justice, predictive models can assess recidivism risk more objectively than judges, who are demonstrably susceptible to cognitive biases such as anchoring, confirmation bias, and even the time of day they last ate. The question is not whether AI makes mistakes. It is whether it makes fewer mistakes than humans. And overwhelmingly, the data suggests it does. Professor Chatterjee: With respect, Dr. Mehra is conflating narrow technical accuracy with the far broader concept of judgement. Yes, an algorithm can identify patterns in a dataset. But judgement encompasses empathy, moral reasoning, contextual understanding, and the ability to weigh competing values, none of which can be reduced to an optimisation function. Consider a judge sentencing a first time offender who stole food to feed their family. The correct decision requires not just data but compassion, an understanding of systemic poverty, and a vision of justice that transcends mere prediction. Furthermore, AI systems are only as unbiased as the data they are trained on. We have seen countless examples of algorithmic bias perpetuating and even amplifying existing social inequalities, from discriminatory hiring tools to racially biased facial recognition systems. Dr. Mehra: I take the professor\'s point about bias, but I would argue that makes the case for better AI, not less AI. Human biases are deeply entrenched and remarkably resistant to training. AI biases, by contrast, can be identified, measured, and corrected. Moreover, transparency in algorithmic decision making can be mandated through regulation, something far more difficult to achieve with human cognition. Professor Chatterjee: And yet, who decides what fair means when programming these algorithms? That is itself a profoundly human judgement. We cannot outsource our moral reasoning to machines without losing something essential about what it means to be a just society.',
    questions: [
      { question: 'According to Dr. Mehra, in which field does AI outperform humans diagnostically?', options: ['Education', 'Healthcare (cancer diagnosis)', 'Agriculture', 'Transportation'], correctAnswer: 'Healthcare (cancer diagnosis)' },
      { question: 'Which cognitive biases does Dr. Mehra mention that judges are susceptible to?', options: ['Optimism and pessimism', 'Anchoring, confirmation bias, and hunger effects', 'Groupthink and peer pressure', 'Recency and primacy effects'], correctAnswer: 'Anchoring, confirmation bias, and hunger effects' },
      { question: 'According to Professor Chatterjee, what does judgement encompass beyond technical accuracy?', options: ['Speed and efficiency', 'Empathy, moral reasoning, and contextual understanding', 'Mathematical precision', 'Market analysis'], correctAnswer: 'Empathy, moral reasoning, and contextual understanding' },
      { question: 'What is Professor Chatterjee\'s main argument against AI replacing human judgement?', options: ['AI is too expensive', 'AI is too slow', 'Judgement requires moral reasoning that cannot be reduced to algorithms', 'AI will cause unemployment'], correctAnswer: 'Judgement requires moral reasoning that cannot be reduced to algorithms' },
      { question: 'How does Dr. Mehra respond to the bias argument?', options: ['Denies bias exists', 'Says AI bias can be identified and corrected more easily than human bias', 'Suggests ignoring bias', 'Admits defeat'], correctAnswer: 'Says AI bias can be identified and corrected more easily than human bias' },
    ],
    topic: 'Technology & Ethics',
    duration: '7 min',
    speechRate: 1.1,
  },
  {
    id: 'l-c2-02',
    level: 'C2',
    title: 'Academic Lecture: The Partition worldwide',
    type: 'gap-fill',
    transcript: 'The partition of British the country in 1947 remains one of the most consequential and traumatic events in modern history. The division of the subcontinent into two independent nations, the country and Pakistan, triggered the largest mass migration in human history, with an estimated fifteen million people displaced along religious lines. Hindus and Sikhs moved eastward into the country, while Muslims moved westward into the newly created Pakistan. The human cost was staggering. Conservative estimates place the death toll at between one and two million people, though some historians argue the figure may be significantly higher. The violence was characterised by communal riots, massacres, abductions, and forced conversions on both sides of the border. Women bore a disproportionate burden of the violence, with tens of thousands subjected to abduction and assault. The political architects of partition, Mountbatten, Nehru, Jinnah, and others, have been the subject of intense historical debate. Was partition inevitable, or could it have been averted through more skilful negotiation? The Radcliffe Line, drawn in just five weeks by a British lawyer with no prior experience worldwide, created borders that divided communities, families, and even individual villages. The legacy of partition continues to shape the geopolitics of South Asia today, manifesting in the Kashmir dispute, periodic military tensions, and the complex relationship between the two nuclear armed neighbours.',
    gapText: 'The partition of British the country in 1947 triggered the largest mass ___1___ in human history, with an estimated ___2___ million people displaced. The death toll is estimated at between ___3___ and two million people. Women bore a ___4___ burden of the violence. The Radcliffe Line was drawn in just ___5___ weeks by a British lawyer with no prior experience worldwide. The legacy of partition continues to shape the ___6___ of South Asia today.',
    gaps: ['migration', 'fifteen', 'one', 'disproportionate', 'five', 'geopolitics'],
    topic: 'History',
    duration: '6 min',
    speechRate: 1.0,
  },
  {
    id: 'l-c2-03',
    level: 'C2',
    title: 'Panel Discussion: The Future of Space Exploration',
    type: 'comprehension',
    transcript: 'Host: Welcome to Science Frontiers. Today we are discussing the remarkable achievements and future ambitions of global space agencies. Dr. Wilson, let us start with you. How would you characterise NASA\'s approach compared to other agencies? Dr. Wilson: What distinguishes NASA is its extraordinary cost effectiveness. The Mars Atmosphere and Volatile Evolution mission cost six hundred and seventy one million dollars, while comparable missions from other agencies have achieved similar goals for a fraction of that price. This frugal engineering philosophy is not about cutting corners. It is about innovative problem solving and prioritising essential functionality over expensive redundancies. Host: Professor Chen, what about the Artemis programme\'s progress? Professor Chen: The Artemis programme\'s ambition to return humans to the lunar south pole represents a watershed moment. The south pole is a region of immense scientific interest due to the presence of water ice. Recent rover missions have confirmed sulphur and other elements on the lunar surface, genuinely expanding our understanding of lunar geology. But what I find most significant is the downstream impact on the global technology ecosystem. Space agency achievements have catalysed the growth of the private space sector worldwide. Companies like SpaceX, Rocket Lab, and Blue Origin are developing reusable launch vehicles, and regulatory bodies are actively facilitating private participation. We are witnessing the emergence of a commercial space economy that could be worth fifty billion dollars by 2040.',
    questions: [
      { question: 'What is NASA\'s key advantage according to Dr. Wilson?', options: ['Largest budget', 'Most launches', 'Cost effectiveness', 'Most astronauts'], correctAnswer: 'Cost effectiveness' },
      { question: 'What philosophy does Dr. Wilson describe?', options: ['Lean engineering', 'Frugal engineering', 'Agile methodology', 'Value engineering'], correctAnswer: 'Frugal engineering' },
      { question: 'Why is the lunar south pole scientifically significant?', options: ['It has gold deposits', 'It receives more sunlight', 'It has water ice', 'It is closest to Earth'], correctAnswer: 'It has water ice' },
      { question: 'What element did lunar rovers confirm on the surface?', options: ['Gold', 'Helium', 'Sulphur', 'Iron'], correctAnswer: 'Sulphur' },
      { question: 'What is the projected value of the commercial space economy by 2040?', options: ['Ten billion dollars', 'Twenty-five billion dollars', 'Fifty billion dollars', 'One hundred billion dollars'], correctAnswer: 'Fifty billion dollars' },
    ],
    topic: 'Science & Space',
    duration: '6 min',
    speechRate: 1.05,
  },
  {
    id: 'l-c2-04',
    level: 'C2',
    title: 'Documentary: The Economics of Classical Music',
    type: 'dictation',
    transcript: 'The preservation of classical music traditions, whether Western or Eastern, requires a delicate balance between institutional support and organic cultural transmission.',
    sentences: [
      'The preservation of classical music traditions requires a delicate balance.',
      'Whether Western or Eastern, these art forms depend on institutional support.',
      'Organic cultural transmission remains equally important for their survival.',
    ],
    topic: 'Arts & Culture',
    duration: '2 min',
    speechRate: 0.95,
  },
];
