import type { CEFRLevel } from '@/lib/firestore';

export interface WritingPrompt {
  id: string;
  level: CEFRLevel;
  title: string;
  instruction: string;
  hint: string;
  minWords: number;
  maxWords: number;
  sampleAnswer?: string;
}

export const writingPrompts: WritingPrompt[] = [
  // ══════════════════════════════════════
  //  A1 – Beginner (10 prompts)
  // ══════════════════════════════════════
  {
    id: 'w-a1-1',
    level: 'A1',
    title: 'Write About Your Day',
    instruction: 'Write 5-8 sentences about what you did today. Use simple past tense (I went, I ate, I saw).',
    hint: 'Start with "Today I woke up at..." and describe your activities.',
    minWords: 30,
    maxWords: 80,
    sampleAnswer: 'Today I woke up at 7 AM. I had tea and roti for breakfast. Then I went to work by bus. I worked on the computer from 9 to 5. After work, I went to the market. I bought vegetables and fruits. I cooked dinner at home. I watched TV and went to sleep at 10 PM.',
  },
  {
    id: 'w-a1-2',
    level: 'A1',
    title: 'Describe Your Home',
    instruction: 'Write about your home. How many rooms does it have? What is your favourite room?',
    hint: 'Use "There is / There are" and adjectives like big, small, clean, cozy.',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-3',
    level: 'A1',
    title: 'My Family',
    instruction: 'Write about your family. How many people are in your family? What do they do? Who do you like spending time with?',
    hint: 'Use simple sentences: "My mother is a teacher. My brother is 10 years old."',
    minWords: 30,
    maxWords: 80,
    sampleAnswer: 'I have a small family. There are four people in my family. My father is a shopkeeper. My mother is a homemaker. She cooks very well. I have one sister. Her name is Sophie. She goes to school. We play together in the evening. I love my family very much.',
  },
  {
    id: 'w-a1-4',
    level: 'A1',
    title: 'My Favourite Food',
    instruction: 'Write about your favourite food. What is it? Who makes it? When do you eat it? Why do you like it?',
    hint: 'Use words like "delicious", "tasty", "spicy", "sweet".',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-5',
    level: 'A1',
    title: 'Introduce Yourself',
    instruction: 'Write a short introduction about yourself. Include your name, age, where you live, what you do, and one thing you like.',
    hint: 'Start with "My name is..." and write simple sentences.',
    minWords: 30,
    maxWords: 80,
    sampleAnswer: 'My name is Thomas. I am 22 years old. I live in Amsterdam, Arizona. I am a college student. I study computer science. I like playing football with my friends. I also like watching movies on weekends.',
  },
  {
    id: 'w-a1-6',
    level: 'A1',
    title: 'My Best Friend',
    instruction: 'Write about your best friend. What is their name? How do you know them? What do you do together?',
    hint: 'Use present tense: "My friend likes...", "We go to..."',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-7',
    level: 'A1',
    title: 'My School or Workplace',
    instruction: 'Write about your school or workplace. Where is it? What do you do there? What time do you go and come back?',
    hint: 'Use time words: "in the morning", "at 9 o\'clock", "after lunch".',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-8',
    level: 'A1',
    title: 'Things I Like and Dislike',
    instruction: 'Write about three things you like and three things you don\'t like. Explain why with simple reasons.',
    hint: 'Use "I like... because..." and "I don\'t like... because...".',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-9',
    level: 'A1',
    title: 'A Weekend Plan',
    instruction: 'Write about what you will do this weekend. Where will you go? Who will you meet? What will you eat?',
    hint: 'Use "I will..." or "I am going to..." for future plans.',
    minWords: 30,
    maxWords: 80,
  },
  {
    id: 'w-a1-10',
    level: 'A1',
    title: 'My Pet or Favourite Animal',
    instruction: 'Write about your pet or your favourite animal. What does it look like? What does it eat? Why do you like it?',
    hint: 'Use "It is...", "It has...", "It likes...".',
    minWords: 30,
    maxWords: 80,
  },

  // ══════════════════════════════════════
  //  A2 – Elementary (10 prompts)
  // ══════════════════════════════════════
  {
    id: 'w-a2-1',
    level: 'A2',
    title: 'Write an Email to a Friend',
    instruction: 'Write a short email inviting a friend to your birthday party. Include the date, time, place, and what to bring.',
    hint: 'Start with "Dear [name]," and end with "Best wishes" or "See you soon!"',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-2',
    level: 'A2',
    title: 'My Last Holiday',
    instruction: 'Write about a holiday or trip you took recently. Where did you go? How did you travel? What did you see and do?',
    hint: 'Use past tense: "I went to...", "We visited...", "I saw...".',
    minWords: 50,
    maxWords: 120,
    sampleAnswer: 'Last month, I went to Goa with my family. We travelled by train from Sydney. It took about 12 hours. We stayed in a small hotel near the beach. Every morning we went to the beach and played in the water. We ate delicious fish curry and rice. We also visited a beautiful old church. I bought some souvenirs for my friends. It was a wonderful holiday and I want to go again.',
  },
  {
    id: 'w-a2-3',
    level: 'A2',
    title: 'My Daily Routine',
    instruction: 'Describe your daily routine from morning to night. Include times and activities.',
    hint: 'Use time expressions: "First, I...", "Then I...", "After that...", "Finally...".',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-4',
    level: 'A2',
    title: 'A Person I Admire',
    instruction: 'Write about someone you admire. It can be a family member, teacher, or famous person. Why do you admire them?',
    hint: 'Use adjectives to describe them: "kind", "hardworking", "brave", "helpful".',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-5',
    level: 'A2',
    title: 'Shopping for Clothes',
    instruction: 'Write about a time you went shopping for clothes. What did you buy? How much did it cost? Did you enjoy it?',
    hint: 'Use words like "shop", "tried on", "expensive", "cheap", "comfortable".',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-6',
    level: 'A2',
    title: 'A Festival I Celebrate',
    instruction: 'Write about a festival you celebrate. What is it called? When is it? What do people do? What do you eat?',
    hint: 'Use present tense for things that happen every year: "We celebrate...", "People wear...".',
    minWords: 50,
    maxWords: 120,
    sampleAnswer: 'New Year is my favourite festival. We celebrate it in October or November. Before New Year, we clean our house and buy new clothes. On New Year day, my mother makes sweets like brownies and cookies. In the evening, we light candles and candles. We put decorations near the door. Children burst firecrackers, but now many people use less crackers because of pollution. We visit our relatives and give them sweets. I love New Year because everyone is happy.',
  },
  {
    id: 'w-a2-7',
    level: 'A2',
    title: 'My Favourite Sport',
    instruction: 'Write about your favourite sport. How often do you play or watch it? Who is your favourite player? Why do you like this sport?',
    hint: 'Use frequency words: "always", "usually", "sometimes", "every weekend".',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-8',
    level: 'A2',
    title: 'Describe a Picture',
    instruction: 'Imagine a picture of a busy global market. Describe what you can see: people, shops, colours, sounds, smells.',
    hint: 'Use "There is/are...", "I can see...", "On the left/right...".',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-9',
    level: 'A2',
    title: 'A Thank-You Note',
    instruction: 'Write a short thank-you note to someone who helped you. Explain what they did and how it made you feel.',
    hint: 'Start with "Dear...", include "Thank you for...", end with a warm closing.',
    minWords: 50,
    maxWords: 120,
  },
  {
    id: 'w-a2-10',
    level: 'A2',
    title: 'My Dream Job',
    instruction: 'Write about the job you want to have in the future. What is it? Why do you want it? What will you do every day?',
    hint: 'Use future tense: "I want to be...", "I will help...", "I hope to...".',
    minWords: 50,
    maxWords: 120,
  },

  // ══════════════════════════════════════
  //  B1 – Intermediate (10 prompts)
  // ══════════════════════════════════════
  {
    id: 'w-b1-1',
    level: 'B1',
    title: 'Opinion: Social Media',
    instruction: 'Write a short paragraph expressing your opinion on social media. Is it helpful or harmful for students? Give reasons.',
    hint: 'Use phrases like "In my opinion...", "I believe...", "On the other hand...".',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-2',
    level: 'B1',
    title: 'Letter of Complaint',
    instruction: 'Write a formal letter to a company complaining about a product you purchased that was damaged.',
    hint: 'Use formal language: "I am writing to express my dissatisfaction with...".',
    minWords: 100,
    maxWords: 250,
  },
  {
    id: 'w-b1-3',
    level: 'B1',
    title: 'Advantages of Learning English',
    instruction: 'Write about why learning English is important in many countries. Give at least three reasons with examples from daily life.',
    hint: 'Use linking words: "Firstly...", "In addition...", "For example...".',
    minWords: 80,
    maxWords: 200,
    sampleAnswer: 'Learning English is very important in many countries for several reasons. Firstly, English is used in most offices and businesses. If you speak English well, you can get better jobs and higher salaries. For example, IT companies in Toronto and Singapore require English for communication.\n\nIn addition, English helps us access knowledge. Most websites, research papers, and online courses are in English. Students who know English can learn from the best universities in the world through the internet.\n\nFinally, English connects people across the region. The country has many languages, and sometimes people from different states cannot understand each other. English acts as a common language that everyone can use. For these reasons, I believe every local student should learn English.',
  },
  {
    id: 'w-b1-4',
    level: 'B1',
    title: 'A Memorable Journey',
    instruction: 'Write about a journey that you remember well. Describe where you went, who you were with, what happened, and why it was memorable.',
    hint: 'Use narrative tenses and descriptive language. Include feelings and reactions.',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-5',
    level: 'B1',
    title: 'Healthy Lifestyle',
    instruction: 'Write an article for a school magazine about how young people in many countries can live a healthier lifestyle. Include tips on food, exercise, and sleep.',
    hint: 'Use advice language: "People should...", "It is important to...", "One way to...".',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-6',
    level: 'B1',
    title: 'Email: Requesting Information',
    instruction: 'Write a semi-formal email to a language school asking about English courses. Ask about schedules, fees, online options, and certification.',
    hint: 'Be polite: "I would like to know...", "Could you please tell me...".',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-7',
    level: 'B1',
    title: 'Review: A Movie or Book',
    instruction: 'Write a review of a movie or book you recently watched or read. Describe the story briefly, give your opinion, and say whether you recommend it.',
    hint: 'Use opinion language and don\'t give away the ending: "I would recommend...", "The best part was...".',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-8',
    level: 'B1',
    title: 'Life in a Big City vs. Village',
    instruction: 'Compare life in a big local city with life in a village. Discuss advantages and disadvantages of each.',
    hint: 'Use comparison language: "While city life offers...", "On the other hand, village life...".',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-9',
    level: 'B1',
    title: 'A Problem in My Neighbourhood',
    instruction: 'Write about a problem in your neighbourhood (traffic, garbage, noise, flooding). Describe the problem and suggest solutions.',
    hint: 'Use problem-solution structure: describe the situation, explain effects, propose fixes.',
    minWords: 80,
    maxWords: 200,
  },
  {
    id: 'w-b1-10',
    level: 'B1',
    title: 'An Unusual Experience',
    instruction: 'Write about an unusual or unexpected experience you had. What happened? How did you react? What did you learn from it?',
    hint: 'Use past tenses and include your feelings: "I was surprised when...", "I felt...".',
    minWords: 80,
    maxWords: 200,
  },

  // ══════════════════════════════════════
  //  B2 – Upper-Intermediate (10 prompts)
  // ══════════════════════════════════════
  {
    id: 'w-b2-1',
    level: 'B2',
    title: 'Essay: Technology in Education',
    instruction: 'Write a short essay discussing the advantages and disadvantages of technology in many countriesn classrooms.',
    hint: 'Use a clear structure: introduction, advantages, disadvantages, conclusion.',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-2',
    level: 'B2',
    title: 'Report: A Local Event',
    instruction: 'Write a report about a recent event in your city (festival, sports match, or cultural event). Include what happened, who was there, and your evaluation.',
    hint: 'Use formal language and organise with subheadings: Introduction, Description, Evaluation.',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-3',
    level: 'B2',
    title: 'Opinion Essay: Online vs. Offline Education',
    instruction: 'Write an essay discussing whether online education is as effective as classroom learning. Consider factors like engagement, accessibility, and quality.',
    hint: 'Present both sides fairly before giving your own opinion. Use evidence and examples.',
    minWords: 150,
    maxWords: 350,
    sampleAnswer: 'The COVID-19 pandemic forced millions worldwiden students to switch to online education almost overnight. While this shift ensured continuity of learning, it also exposed significant challenges that raise questions about online education\'s effectiveness compared to traditional classrooms.\n\nOn the positive side, online education offers remarkable accessibility. Students in remote villages can access lectures from top universities through platforms like NPTEL and SWAYAM. It also provides flexibility—learners can study at their own pace and revisit recorded sessions. Furthermore, the cost of online courses is generally lower than traditional education.\n\nHowever, online learning has notable limitations. Many local households lack reliable internet connectivity, particularly in rural areas. Students often struggle with motivation and discipline without the structure of a physical classroom. Additionally, practical subjects such as laboratory science and physical education cannot be effectively taught online. The lack of face-to-face interaction also affects social development.\n\nIn my opinion, a blended approach combining online resources with regular classroom interaction offers the best of both worlds. Technology should supplement, not replace, the irreplaceable human element of education.',
  },
  {
    id: 'w-b2-4',
    level: 'B2',
    title: 'Formal Letter: Job Application',
    instruction: 'Write a cover letter applying for a position as a content writer at a digital marketing company. Highlight your skills, experience, and why you are a good fit.',
    hint: 'Use formal professional tone. Structure: introduction, qualifications, motivation, closing.',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-5',
    level: 'B2',
    title: 'Essay: Environmental Challenges in many countries',
    instruction: 'Write about the major environmental challenges the country faces today. Discuss causes, effects, and possible solutions. Focus on one or two issues in depth.',
    hint: 'Use cause-effect language: "This leads to...", "As a result...", "One solution would be...".',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-6',
    level: 'B2',
    title: 'Article: The Gig Economy',
    instruction: 'Write an article for a news website about the rise of the gig economy in many countries. Discuss platforms like Uber Eats, Uber, and TaskRabbit, and the impact on workers.',
    hint: 'Include facts, different perspectives (workers, companies, consumers), and balanced analysis.',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-7',
    level: 'B2',
    title: 'Review: A Restaurant or Café',
    instruction: 'Write a detailed review of a restaurant or café you visited. Describe the ambiance, food, service, and value for money. Give a recommendation.',
    hint: 'Use evaluative language: "The atmosphere was...", "One highlight was...", "I would suggest...".',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-8',
    level: 'B2',
    title: 'Discussion: Should Exams Be Abolished?',
    instruction: 'Write a discussion essay exploring whether traditional exams should be replaced with continuous assessment in many countriesn schools and universities.',
    hint: 'Present arguments for and against, and include a nuanced conclusion.',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-9',
    level: 'B2',
    title: 'Proposal: Improving Public Transport',
    instruction: 'Write a proposal to your city\'s municipal corporation suggesting improvements to the public transport system. Include current problems and specific recommendations.',
    hint: 'Use formal proposal language: "I propose that...", "This would result in...", "The key benefits include...".',
    minWords: 150,
    maxWords: 350,
  },
  {
    id: 'w-b2-10',
    level: 'B2',
    title: 'Narrative: A Day That Changed My Perspective',
    instruction: 'Write about a day or event that changed the way you think about something. Describe what happened and explain how your perspective changed.',
    hint: 'Use reflective language: "Before this experience, I thought...", "I came to realise that...".',
    minWords: 150,
    maxWords: 350,
  },

  // ══════════════════════════════════════
  //  C1 – Advanced (10 prompts)
  // ══════════════════════════════════════
  {
    id: 'w-c1-1',
    level: 'C1',
    title: 'Critical Essay: Data Privacy in many countries',
    instruction: 'Write a well-structured essay analysing the tension between digital innovation and individual privacy in many countries. Reference national ID system, digital payments, or the Data Protection Act.',
    hint: 'Present multiple perspectives. Use advanced linking words: "notwithstanding", "conversely", "insofar as".',
    minWords: 200,
    maxWords: 450,
    sampleAnswer: 'the country\'s digital transformation has been nothing short of revolutionary. The national ID system biometric identification system, covering over 1.3 billion residents, has streamlined access to government services and financial inclusion. Similarly, the Unified Payments Interface (digital payments) has democratised digital transactions, processing billions monthly.\n\nHowever, this rapid digitisation raises profound questions about individual privacy. The Supreme Court\'s 2017 the landmark ruling judgement unequivocally established privacy as a fundamental right, yet the subsequent Data Protection Act of 2023 has drawn criticism for granting the state broad exemptions.\n\nNotwithstanding these concerns, proponents argue that a regulatory framework—however imperfect—is preferable to the legal vacuum that preceded it. Conversely, civil liberties advocates contend that without robust safeguards, centralised databases become instruments of surveillance rather than empowerment.\n\nIn conclusion, the country must strike a delicate balance: harnessing technology for inclusive development while ensuring that the constitutional promise of privacy is not sacrificed at the altar of efficiency.',
  },
  {
    id: 'w-c1-2',
    level: 'C1',
    title: 'Formal Proposal: Workplace Improvement',
    instruction: 'Write a formal proposal to your company\'s management suggesting improvements to employee well-being and productivity. Include an analysis of the current situation, specific recommendations, and expected outcomes.',
    hint: 'Use formal register, hedging language ("It would appear that..."), and clear section structure.',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-3',
    level: 'C1',
    title: 'Argumentative Essay: Urbanisation in many countries',
    instruction: 'Write an essay arguing whether rapid urbanisation in many countries is a net positive or negative for the country. Consider economic growth, infrastructure strain, migration, and social impact.',
    hint: 'Take a clear position, acknowledge counterarguments, and use sophisticated transitions.',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-4',
    level: 'C1',
    title: 'Analysis: Media Influence on Public Opinion',
    instruction: 'Write an analytical piece examining how local news media and social media shape public opinion on political and social issues. Discuss bias, echo chambers, and media literacy.',
    hint: 'Use analytical language: "This phenomenon can be attributed to...", "A nuanced examination reveals...".',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-5',
    level: 'C1',
    title: 'Essay: The Future of Work in many countries',
    instruction: 'Write an essay exploring how automation, AI, and remote work are transforming the local job market. Discuss which sectors are most affected and how workers can adapt.',
    hint: 'Use speculative and evaluative language: "It is conceivable that...", "The implications of this trend...".',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-6',
    level: 'C1',
    title: 'Opinion Piece: Reservation Policy',
    instruction: 'Write a balanced opinion piece discussing the pros and cons worldwide\'s reservation (affirmative action) policies in education and employment. Present multiple viewpoints before stating your own position.',
    hint: 'Handle this sensitive topic with nuance. Use hedging: "While it is true that...", "One might argue...".',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-7',
    level: 'C1',
    title: 'Report: State worldwiden Healthcare',
    instruction: 'Write a formal report assessing the current state of healthcare in many countries. Cover public vs. private healthcare, rural access, government schemes like Ayushman Bharat, and recommendations.',
    hint: 'Use report structure: Executive Summary, Current Situation, Key Issues, Recommendations.',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-8',
    level: 'C1',
    title: 'Critical Review: A Contemporary Novel',
    instruction: 'Write a critical review of a contemporary English novel (e.g., by Kazuo Ishiguro, Chimamanda Ngozi Adichie, Margaret Atwood, or Haruki Murakami). Analyse themes, style, and cultural significance.',
    hint: 'Go beyond summary—analyse literary techniques, cultural context, and the author\'s craft.',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-9',
    level: 'C1',
    title: 'Essay: local Education System Reform',
    instruction: 'Write a well-argued essay evaluating the National Education Policy (Education Reform Act) 2020 and its potential to transform the country\'s education system. Discuss strengths, weaknesses, and implementation challenges.',
    hint: 'Reference specific policy provisions. Use academic register and evidence-based arguments.',
    minWords: 200,
    maxWords: 450,
  },
  {
    id: 'w-c1-10',
    level: 'C1',
    title: 'Discursive Essay: Is English a Colonial Legacy or a Global Necessity?',
    instruction: 'Write an essay exploring the complex role of English in many countries — as a remnant of colonialism, a tool for social mobility, and a global lingua franca. Consider perspectives of different socioeconomic groups.',
    hint: 'Engage with the complexity. Use sophisticated discourse markers: "Herein lies the paradox...", "Insofar as...".',
    minWords: 200,
    maxWords: 450,
  },

  // ══════════════════════════════════════
  // C2 – Band 8-9: Expert-Level Writing
  // ══════════════════════════════════════
  {
    id: 'w-c2-1',
    level: 'C2',
    title: 'Discursive Essay: The Ethics of Artificial Intelligence',
    instruction: 'Write a nuanced essay examining the ethical implications of deploying artificial intelligence in high-stakes domains such as healthcare, criminal justice, and autonomous warfare. Address issues of accountability, bias, and the limits of algorithmic decision-making.',
    hint: 'Use sophisticated hedging: "It is incumbent upon...", "The ramifications of... are far-reaching." Present a thesis, counterarguments, and a synthesised conclusion.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-2',
    level: 'C2',
    title: 'Critical Analysis: The Post-Truth Era',
    instruction: 'Write a critical analysis of the concept of "post-truth" politics. Examine how digital media ecosystems, algorithmic content curation, and the erosion of institutional authority have transformed public discourse. Reference specific examples.',
    hint: 'Employ academic register: "This phenomenon is predicated upon...", "A closer scrutiny reveals..." Include references to philosophical concepts.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-3',
    level: 'C2',
    title: 'Argumentative Essay: Universal Basic Income',
    instruction: 'Construct a rigorous argument either for or against the implementation of a Universal Basic Income (UBI). Address economic feasibility, the psychological impact of unconditional transfers, labour market effects, and philosophical objections.',
    hint: 'Anticipate and refute counterarguments systematically. Use conditional and subjunctive constructions: "Were governments to implement...", "It is imperative that policymakers consider...".',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-4',
    level: 'C2',
    title: 'Academic Essay: Consciousness and Machine Intelligence',
    instruction: 'Write an academic essay exploring whether artificial systems can ever achieve genuine consciousness. Discuss the "hard problem" of consciousness, the Chinese Room argument, and Integrated Information Theory.',
    hint: 'Use precise philosophical terminology: "qualia", "phenomenal experience", "functionalism." Structure with clear thesis, argumentation, and synthesis.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-5',
    level: 'C2',
    title: 'Opinion Piece: The Limits of Free Speech',
    instruction: 'Write a sophisticated opinion piece addressing where the limits of free speech should lie in democratic societies. Consider hate speech legislation, academic freedom, the paradox of tolerance, and the role of social media platforms as de facto public squares.',
    hint: 'Balance competing rights and principles. Use nuanced qualifiers: "Notwithstanding the merits of...", "Insofar as... is concerned...".',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-6',
    level: 'C2',
    title: 'Analytical Report: Global Migration Patterns',
    instruction: 'Write a formal analytical report examining the causes, patterns, and consequences of global migration in the twenty-first century. Cover economic migration, climate refugees, and the political responses in host countries.',
    hint: 'Use report conventions: executive summary language, evidence-based assertions, and policy recommendations. Employ formal connectives throughout.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-7',
    level: 'C2',
    title: 'Essay: The Paradox of Choice',
    instruction: 'Write an essay exploring how the proliferation of choice in consumer societies can paradoxically diminish well-being. Draw on research in behavioural economics and psychology to support your analysis.',
    hint: 'Reference concepts like "decision fatigue", "opportunity cost", and "satisficing vs. maximising." Use sophisticated cause-effect structures.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-8',
    level: 'C2',
    title: 'Critical Review: A Contemporary Non-Fiction Work',
    instruction: 'Write a critical review of a significant non-fiction book published in the last decade (e.g., Sapiens by Harari, Thinking Fast and Slow by Kahneman, or The Uninhabitable Earth by Wallace-Wells). Evaluate the argument, evidence, and rhetorical strategies employed.',
    hint: 'Go beyond summary: critically assess methodology, identify logical fallacies, and situate the work within its intellectual tradition.',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-9',
    level: 'C2',
    title: 'Persuasive Letter: Climate Policy Advocacy',
    instruction: 'Write a persuasive open letter to world leaders ahead of a climate summit, advocating for specific, actionable policies. Combine emotional appeal with rigorous evidence and acknowledge the economic trade-offs involved.',
    hint: 'Master the art of persuasion at the highest level: "The scientific consensus is unequivocal...", "The moral imperative demands...", "History will judge us by...".',
    minWords: 250,
    maxWords: 500,
  },
  {
    id: 'w-c2-10',
    level: 'C2',
    title: 'Philosophical Essay: The Nature of Knowledge',
    instruction: 'Write a philosophical essay exploring the question: "Is absolute knowledge achievable, or are all claims to truth inherently provisional?" Draw on epistemological frameworks such as empiricism, rationalism, and Popperian falsificationism.',
    hint: 'Demonstrate mastery of academic argumentation: define terms precisely, construct logical chains, and acknowledge the limitations of your own position.',
    minWords: 250,
    maxWords: 500,
  },
];

export function getWritingPromptsByLevel(level: CEFRLevel): WritingPrompt[] {
  return writingPrompts.filter((p) => p.level === level);
}

export function getWritingPromptById(id: string): WritingPrompt | undefined {
  return writingPrompts.find((p) => p.id === id);
}
